### ISSUE TITLE
Can only bake animation curves when no time range is specified

### ISSUE THREAD

**Issue by OlivierArgentieri** [ArtFXDev/silex_maya#100]

**Comment by OlivierArgentieri** [comment]
```
Traceback (most recent call last): 
File "d:\rez\dev_packages\pullgithub_artfx\silex_client\dev\silex_client\action\command_buffer.py", line 127, in execute await self.executor(parameters, action_query, log) 
File "d:\rez\dev_packages\pullgithub_artfx\silex_client\dev\silex_client\action\command_base.py", line 125, in wrapper_conform_command output = await func(command, *args, **kwargs) 
File "d:\rez\dev_packages\pullgithub_artfx\silex_maya\dev\silex_maya\commands\export_fbx.py", line 123, in __call__ await Utils.wrapped_execute(action_query, export_fbx, export_path, selected, used_timeline, start_frame, end_frame)
File "d:\rez\dev_packages\pullgithub_artfx\silex_maya\dev\silex_maya\utils\utils.py", line 48, in wrapped_execute await asyncio.wait_for(future, None) 
File "C:\Maya2022\Maya2022\Python37\lib\asyncio\tasks.py", line 414, in wait_for return await fut 
File "d:\rez\dev_packages\pullgithub_artfx\silex_maya\dev\silex_maya\utils\utils.py", line 24, in wrapped_function result = maya_function(*args, **kwargs) 
File "d:\rez\dev_packages\pullgithub_artfx\silex_maya\dev\silex_maya\commands\export_fbx.py", line 85, in export_fbx cmds.bakeSimulation(object_list) 
# Needed RuntimeError: Can only bake animation curves when no time range is specified
```
